#!/bin/sh

if ! systemctl --user is-active --quiet pipewire 2>/dev/null; then
    pipewire &
    sleep 0.5
    wireplumber &
    pipewire-pulse &
fi

if ! systemctl --user is-active --quiet mpd 2>/dev/null; then
    [ ! -s ~/.config/mpd/pid ] && mpd
fi

# fuck capslock
setxkbmap -option caps:none &

############## INSERT YOUR XRANDR COMMANDS HERE ###############
xrandr --output eDP-1 --mode 2560x1600 &

picom &
dunst &
dwmstatus &

xautolock -time 2 -locker slock &

wallpaper random &

exec ssh-agent dwm
