#!/bin/sh

# audio 
pipewire &
sleep 0.5
wireplumber &

# mpd
mpd &

# compositor
picom -c --no-fading-openclose --backend glx &

# notification server
dunst &

# display resolution
# insert your xrandr commands here

# fuck capslock
setxkbmap -option caps:none

# set wallpaper
wallpaper

# execute dwm
while true; do
    dwm >/dev/null 2>&1
done
